// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbgjguiNSGHa1JpsXM2Y03_pUJjgOio_w',
    appId: '1:252637498518:web:be30a4e14e0d18367346b7',
    messagingSenderId: '252637498518',
    projectId: 'lak-fitness-2',
    authDomain: 'lak-fitness-2.firebaseapp.com',
    storageBucket: 'lak-fitness-2.appspot.com',
    measurementId: 'G-9W97W1S26R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrQorAGSH4Ipkbv8fXWOphjIURSLbPNvU',
    appId: '1:252637498518:android:ddf67b354b05279c7346b7',
    messagingSenderId: '252637498518',
    projectId: 'lak-fitness-2',
    storageBucket: 'lak-fitness-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30oiNSSXvRYSaz5j4sG6FJTGRmHKFWz8',
    appId: '1:252637498518:ios:e81d73a33f4f76457346b7',
    messagingSenderId: '252637498518',
    projectId: 'lak-fitness-2',
    storageBucket: 'lak-fitness-2.appspot.com',
    iosBundleId: 'com.example.lakFitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD30oiNSSXvRYSaz5j4sG6FJTGRmHKFWz8',
    appId: '1:252637498518:ios:bd85b0ac7825eccc7346b7',
    messagingSenderId: '252637498518',
    projectId: 'lak-fitness-2',
    storageBucket: 'lak-fitness-2.appspot.com',
    iosBundleId: 'com.example.lakFitness.RunnerTests',
  );
}
